export type Vendor={id:string;name:string;category:string;contact:string;email:string;phone:string;website:string;taxId:string;address:string;description:string;status:string;ownerId:string|null;createdAt:string;score:number|null;reviews:number};
export type Review={id:string;vendorId:string;reviewer:string;quality:number;price:number;delivery:number;service:number;reliability:number;comment:string;createdAt:string};
export type Profile={id:string;name:string;email:string;role:'admin'|'vendor'};
export const criteria=[['quality','Quality','Products and services meet expectations'],['price','Price & value','Fair pricing for the value delivered'],['delivery','Delivery','On time, with everything as agreed'],['service','Service','Responsive and easy to work with'],['reliability','Reliability','Consistent and dependable']] as const;
const samples=[['1','Atlas Supply Co.','Office supplies','Olivia Chen','Active'],['2','Nexora Technologies','Technology','James Wilson','Active'],['3','Greenline Logistics','Logistics','Emma Miller','Active'],['4','Studio Forma','Professional services','Daniel Park','Pending'],['5','Pacific Packaging','Manufacturing','Sophia Lee','Active'],['6','Horizon Facilities','Facilities','Noah Taylor','Pending'],['7','Vertex Industrial','Manufacturing','Liam Brooks','Inactive']] as const;
export const demoReviews:Review[]=['1','2','3','5','7'].map((id,i)=>({id:'r'+id,vendorId:id,reviewer:'Alex Morgan',quality:[5,5,4,4,3][i],price:4,delivery:[5,4,5,4,3][i],service:[5,5,4,5,3][i],reliability:[5,5,5,4,3][i],comment:'Reliable communication and consistent service throughout this review period.',createdAt:'2026-10-0'+(3-i%3)+'T08:00:00Z'}));
export const average=(r:Review)=>(r.quality+r.price+r.delivery+r.service+r.reliability)/5;
export const demoVendors:Vendor[]=samples.map(([id,name,category,contact,status])=>({id,name,category,contact,status,score:demoReviews.find(r=>r.vendorId===id)?average(demoReviews.find(r=>r.vendorId===id)!):null,reviews:demoReviews.filter(r=>r.vendorId===id).length,email:contact.split(' ')[0].toLowerCase()+'@example.com',phone:'+66 2 000 0000',website:'',taxId:'',address:'Bangkok, Thailand',description:'Sample company profile for exploring the workspace.',ownerId:null,createdAt:'2026-10-01T09:00:00Z'}));
export const categories=['Office supplies','Technology','Logistics','Professional services','Manufacturing','Facilities','Other'];
