'use client';
import {useState} from 'react';
import {Building2,ShieldCheck} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Label} from '@/components/ui/label';
import {Textarea} from '@/components/ui/textarea';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Button} from '@/components/ui/button';
import {criteria,categories,type Vendor} from './data';
import {vendorInput} from './validation';
const th:Record<string,string>={'YOUR ACCOUNT':'บัญชีของคุณ','Your full name':'ชื่อ-นามสกุล','COMPANY INFORMATION':'ข้อมูลบริษัท','Company name':'ชื่อบริษัท','Category':'หมวดหมู่','Choose a category':'เลือกหมวดหมู่','Contact person':'ผู้ติดต่อ','Phone number':'หมายเลขโทรศัพท์','Business email':'อีเมลธุรกิจ','Website':'เว็บไซต์','Tax / registration ID':'เลขประจำตัวผู้เสียภาษี / ทะเบียน','Company address':'ที่อยู่บริษัท','About your company':'เกี่ยวกับบริษัท','Tell us what your company provides.':'ระบุสินค้าและบริการของบริษัท','Your company profile will be submitted for review. Only your company and the workspace administrator can access it.':'ข้อมูลบริษัทจะถูกส่งเพื่อตรวจสอบ โดยมีเพียงบริษัทของคุณและผู้ดูแลพื้นที่ทำงานที่เข้าถึงได้','Saving…':'กำลังบันทึก…','Register company':'ลงทะเบียนบริษัท','Save changes':'บันทึกการเปลี่ยนแปลง','Add vendor':'เพิ่มผู้ขาย','Please try again.':'โปรดลองอีกครั้ง','Workspace name':'ชื่อพื้นที่ทำงาน','You will be the workspace administrator. Vendors who join can register their own company; you can evaluate their performance.':'คุณจะเป็นผู้ดูแลพื้นที่ทำงาน ผู้ขายที่เข้าร่วมสามารถลงทะเบียนบริษัทของตนเอง และคุณสามารถประเมินผลการดำเนินงานได้','Creating…':'กำลังสร้าง…','Create workspace':'สร้างพื้นที่ทำงาน','Vendor':'ผู้ขาย','Choose a vendor':'เลือกผู้ขาย','1 Needs improvement · 3 Meets expectations · 5 Excellent':'1 ควรปรับปรุง · 3 ตามมาตรฐาน · 5 ยอดเยี่ยม','Overall score':'คะแนนรวม','Equal weight across all 5 criteria':'ให้น้ำหนักเท่ากันทั้ง 5 ด้าน','Feedback for the vendor':'ข้อเสนอแนะสำหรับผู้ขาย','What went well? What could improve?':'สิ่งที่ทำได้ดีและสิ่งที่ควรปรับปรุง','This feedback is visible to the vendor.':'ผู้ขายจะเห็นข้อเสนอแนะนี้','Save evaluation':'บันทึกผลประเมิน','Select a vendor and score all five criteria.':'เลือกผู้ขายและให้คะแนนครบทั้งห้าด้าน'};
const tr=(value:string,language:string)=>language==='th'?(th[value]||value):value;
type Submit=(payload:Record<string,unknown>)=>Promise<void>;
function Field({name,label,value='',type='text',required=false,maxLength=160}:{name:string;label:string;value?:string;type?:string;required?:boolean;maxLength?:number}){return <div className="form-field"><Label htmlFor={name}>{label}{required&&<span className="required-mark">*</span>}</Label><Input id={name} name={name} type={type} defaultValue={value} required={required} maxLength={maxLength}/></div>}
function ErrorMessage({error}:{error:string}){return error?<p className="form-error" role="alert">{error}</p>:null}
export function CompanyForm({vendor,registration=false,userName='',submit,language='en'}:{vendor?:Vendor;registration?:boolean;userName?:string;submit:Submit;language?:string}){
 const [category,setCategory]=useState(vendor?.category||''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[createId]=useState(()=>crypto.randomUUID());
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=new FormData(e.currentTarget);const company={name:String(form.get('companyName')||''),category,contact:String(form.get('contact')||''),email:String(form.get('email')||''),phone:String(form.get('phone')||''),website:String(form.get('website')||''),taxId:String(form.get('taxId')||''),address:String(form.get('address')||''),description:String(form.get('description')||'')};const result=vendorInput.safeParse(company);if(!result.success){setError(result.error.issues[0].message);return;}setBusy(true);setError('');try{await submit(registration?{action:'register',data:{name:String(form.get('profileName')||''),company:result.data}}:{action:'saveVendor',id:vendor?.id,createId,data:result.data});}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}
 return <form onSubmit={save} className="app-form">{registration&&<><div className="form-section-label">{tr('YOUR ACCOUNT',language)}</div><Field name="profileName" label={tr('Your full name',language)} value={userName} required maxLength={100}/><div className="form-section-label">{tr('COMPANY INFORMATION',language)}</div></>}<Field name="companyName" label={tr('Company name',language)} value={vendor?.name} required maxLength={120}/><div className="form-field"><Label htmlFor="companyCategory">{tr('Category',language)}<span className="required-mark">*</span></Label><Select value={category} onValueChange={setCategory}><SelectTrigger id="companyCategory"><SelectValue placeholder={tr('Choose a category',language)}/></SelectTrigger><SelectContent>{categories.map(c=><SelectItem key={c} value={c}>{c}</SelectItem>)}</SelectContent></Select></div><div className="form-two"><Field name="contact" label={tr('Contact person',language)} value={vendor?.contact||userName} required maxLength={100}/><Field name="phone" label={tr('Phone number',language)} value={vendor?.phone} type="tel" required maxLength={40}/></div><Field name="email" label={tr('Business email',language)} value={vendor?.email} type="email" required/><div className="form-two"><Field name="website" label={tr('Website',language)} value={vendor?.website} type="url" maxLength={250}/><Field name="taxId" label={tr('Tax / registration ID',language)} value={vendor?.taxId} maxLength={40}/></div><Field name="address" label={tr('Company address',language)} value={vendor?.address} maxLength={500}/><div className="form-field"><Label htmlFor="description">{tr('About your company',language)}</Label><Textarea id="description" name="description" defaultValue={vendor?.description||''} maxLength={1000} placeholder={tr('Tell us what your company provides.',language)} rows={3}/></div>{registration&&<p className="form-note"><ShieldCheck size={16}/>{tr('Your company profile will be submitted for review. Only your company and the workspace administrator can access it.',language)}</p>}<ErrorMessage error={error}/><Button type="submit" disabled={busy} className="form-submit">{tr(busy?'Saving…':registration?'Register company':vendor?'Save changes':'Add vendor',language)}</Button></form>
}
export function SetupForm({name,submit,language='en'}:{name:string;submit:Submit;language?:string}){const [busy,setBusy]=useState(false),[error,setError]=useState('');async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const fd=new FormData(e.currentTarget);setBusy(true);setError('');try{await submit({action:'setup',data:{name:String(fd.get('profileName')),workspaceName:String(fd.get('workspaceName'))}});}catch(e){setError(e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}}return <form onSubmit={save} className="app-form"><div className="setup-icon"><Building2 size={25}/></div><Field name="profileName" label={tr('Your full name',language)} value={name} required maxLength={100}/><Field name="workspaceName" label={tr('Workspace name',language)} value="Vendor workspace" required maxLength={120}/><p className="form-note">{tr('You will be the workspace administrator. Vendors who join can register their own company; you can evaluate their performance.',language)}</p><ErrorMessage error={error}/><Button type="submit" disabled={busy} className="form-submit">{tr(busy?'Creating…':'Create workspace',language)}</Button></form>}
export function ReviewForm({vendors,vendorId,submit,language='en'}:{vendors:Vendor[];vendorId?:string;submit:Submit;language?:string}){
 const [chosen,setChosen]=useState(vendorId||''),[scores,setScores]=useState<Record<string,number>>({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[id]=useState(()=>crypto.randomUUID());
 const complete=criteria.every(([key])=>scores[key]),avg=complete?criteria.reduce((sum,[key])=>sum+scores[key],0)/5:null;
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;if(!chosen||!complete){setError(tr('Select a vendor and score all five criteria.',language));return;}const fd=new FormData(e.currentTarget);setError('');setBusy(true);try{await submit({action:'review',data:{id,vendorId:chosen,...scores,comment:String(fd.get('comment')||'')}});}catch(e){setError(e instanceof Error?e.message:tr('Please try again.',language));}finally{setBusy(false);}}
 return <form className="app-form" onSubmit={save}><div className="form-field"><Label htmlFor="reviewVendor">{tr('Vendor',language)}</Label><Select value={chosen} onValueChange={setChosen}><SelectTrigger id="reviewVendor"><SelectValue placeholder={tr('Choose a vendor',language)}/></SelectTrigger><SelectContent>{vendors.map(v=><SelectItem key={v.id} value={v.id}>{v.name}</SelectItem>)}</SelectContent></Select></div><div className="rating-guide">{tr('1 Needs improvement · 3 Meets expectations · 5 Excellent',language)}</div><div className="score-inputs">{criteria.map(([key,label,description])=><div className="score-input" key={key}><div><Label id={'label-'+key}>{tr(label,language)}</Label><p>{tr(description,language)}</p></div><RadioGroup aria-labelledby={'label-'+key} value={scores[key]?String(scores[key]):''} onValueChange={value=>setScores(s=>({...s,[key]:Number(value)}))} className="rating-radio">{[1,2,3,4,5].map(n=><div className="rating-choice" key={n}><RadioGroupItem id={key+n} value={String(n)} aria-label={`${tr(label,language)}: ${n} ${language==='th'?'จาก':'out of'} 5`}/><Label htmlFor={key+n}>{n}</Label></div>)}</RadioGroup></div>)}</div><div className="review-total"><span>{tr('Overall score',language)}<small>{tr('Equal weight across all 5 criteria',language)}</small></span><strong>{avg?.toFixed(1)||'—'}<small>/ 5</small></strong></div><div className="form-field"><Label htmlFor="comment">{tr('Feedback for the vendor',language)}</Label><Textarea id="comment" name="comment" maxLength={1500} rows={3} placeholder={tr('What went well? What could improve?',language)}/><p className="form-note">{tr('This feedback is visible to the vendor.',language)}</p></div><ErrorMessage error={error}/><Button type="submit" disabled={busy} className="form-submit">{tr(busy?'Saving…':'Save evaluation',language)}</Button></form>
}
