import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/db/raw';
import {vendorInput,registrationInput,setupInput,reviewInput} from '@/app/validation';
import type {Profile,Vendor,Review} from '@/app/data';
export const dynamic='force-dynamic';
const vendorSelect=`SELECT v.id,v.owner_id AS ownerId,v.name,v.category,v.contact,v.email,v.phone,v.website,v.tax_id AS taxId,v.address,v.description,v.status,v.created_at AS createdAt,COUNT(r.id) AS reviews,AVG((r.quality+r.price+r.delivery+r.service+r.reliability)/5.0) AS score FROM vendors v LEFT JOIN reviews r ON r.vendor_id=v.id`;
const reviewSelect=`SELECT r.id,r.vendor_id AS vendorId,r.reviewer,r.quality,r.price,r.delivery,r.service,r.reliability,r.comment,r.created_at AS createdAt FROM reviews r JOIN vendors v ON v.id=r.vendor_id`;
const response=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store'}});
async function account(id:string){return database().prepare('SELECT id,name,email,role FROM accounts WHERE id=?').bind(id).first<Profile>();}
async function state(id:string){const db=database(),profile=await account(id),workspace=await db.prepare('SELECT name,admin_id AS adminId FROM workspace WHERE id=1').first<{name:string;adminId:string}>();if(!profile)return {profile:null,adminExists:!!workspace,workspaceName:workspace?.name||'Vendor workspace',vendors:[],reviews:[]};const admin=profile.role==='admin';const [vs,rs]=await Promise.all([db.prepare(vendorSelect+(admin?'':' WHERE v.owner_id=?')+' GROUP BY v.id ORDER BY v.created_at DESC').bind(...(admin?[]:[id])).all<Vendor>(),db.prepare(reviewSelect+(admin?'':' WHERE v.owner_id=?')+' ORDER BY r.created_at DESC').bind(...(admin?[]:[id])).all<Review>()]);return {profile,adminExists:true,workspaceName:workspace?.name||'Vendor workspace',vendors:vs.results,reviews:rs.results};}
export async function GET(){const user=await getChatGPTUser();if(!user)return response({error:'Sign in to access your workspace.'},401);try{return response(await state(user.userId));}catch(error){console.error('Workspace load failed',error);return response({error:'Your workspace is temporarily unavailable. Please try again.'},503);}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return response({error:'Sign in before saving.'},401);const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin)return response({error:'This request is not allowed.'},403);if(!request.headers.get('content-type')?.startsWith('application/json'))return response({error:'Send a valid form.'},400);try{const raw=await request.text();if(raw.length>16000)return response({error:'This form is too large.'},413);let body;try{body=JSON.parse(raw);}catch{return response({error:'Invalid form.'},400);}const db=database(),profile=await account(user.userId),now=new Date().toISOString();
 if(body.action==='setup'){
  const parsed=setupInput.safeParse(body.data);if(!parsed.success)return response({error:parsed.error.issues[0].message},400);if(profile){const owner=await db.prepare('SELECT admin_id AS adminId FROM workspace WHERE id=1').first<{adminId:string}>();if(profile.role==='admin'&&owner?.adminId===user.userId)return response({...await state(user.userId),recovered:true});return response({error:'Your account is already registered.'},409);}
  const {name,workspaceName}=parsed.data;
  await db.batch([db.prepare('INSERT OR IGNORE INTO workspace (id,admin_id,name,created_at) VALUES (1,?,?,?)').bind(user.userId,workspaceName,now),db.prepare("INSERT OR IGNORE INTO accounts (id,name,email,role,created_at) SELECT ?,?,?,'admin',? WHERE EXISTS (SELECT 1 FROM workspace WHERE id=1 AND admin_id=?)").bind(user.userId,name,user.email,now,user.userId)]);
  const current=await account(user.userId);if(current?.role!=='admin')return response({error:'This workspace is already set up. Register your company instead.'},409);
 }else if(body.action==='register'){
  if(profile){if(profile.role==='vendor')return response({...await state(user.userId),recovered:true});return response({error:'Your account is already registered as an administrator.'},409);}if(!await db.prepare('SELECT id FROM workspace WHERE id=1').first())return response({error:'The workspace owner needs to complete setup first.'},409);
  const parsed=registrationInput.safeParse(body.data);if(!parsed.success)return response({error:parsed.error.issues[0].message},400);const v=parsed.data.company;
  await db.batch([db.prepare("INSERT OR IGNORE INTO accounts (id,name,email,role,created_at) VALUES (?,?,?,'vendor',?)").bind(user.userId,parsed.data.name,user.email,now),db.prepare("INSERT INTO vendors (id,owner_id,name,category,contact,email,phone,website,tax_id,address,description,status,created_at) SELECT ?,?,?,?,?,?,?,?,?,?,?,'Pending',? WHERE NOT EXISTS (SELECT 1 FROM vendors WHERE owner_id=?)").bind(crypto.randomUUID(),user.userId,v.name,v.category,v.contact,v.email,v.phone,v.website,v.taxId,v.address,v.description,now,user.userId)]);
 }else{
  if(!profile)return response({error:'Complete registration first.'},403);
  if(body.action==='saveVendor'){
   const parsed=vendorInput.safeParse(body.data);if(!parsed.success)return response({error:parsed.error.issues[0].message},400);const v=parsed.data;
   if(body.id){if(typeof body.id!=='string')return response({error:'Invalid vendor.'},400);const existing=await db.prepare('SELECT id,owner_id AS ownerId FROM vendors WHERE id=?').bind(body.id).first<{id:string;ownerId:string|null}>();if(!existing||(profile.role!=='admin'&&existing.ownerId!==user.userId))return response({error:'You cannot edit this vendor.'},403);
    await db.prepare('UPDATE vendors SET name=?,category=?,contact=?,email=?,phone=?,website=?,tax_id=?,address=?,description=? WHERE id=?').bind(v.name,v.category,v.contact,v.email,v.phone,v.website,v.taxId,v.address,v.description,body.id).run();
   }else{if(profile.role!=='admin')return response({error:'Only administrators can add vendors.'},403);if(typeof body.createId!=='string'||!/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/i.test(body.createId))return response({error:'Invalid creation reference.'},400);await db.prepare("INSERT OR IGNORE INTO vendors (id,name,category,contact,email,phone,website,tax_id,address,description,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,'Pending',?)").bind(body.createId,v.name,v.category,v.contact,v.email,v.phone,v.website,v.taxId,v.address,v.description,now).run();const saved=await db.prepare('SELECT name,category,contact,email,phone,website,tax_id AS taxId,address,description,owner_id AS ownerId FROM vendors WHERE id=?').bind(body.createId).first<Record<string,unknown>>();if(!saved||saved.ownerId!==null||Object.entries(v).some(([key,value])=>saved[key]!==value))return response({error:'This save reference already belongs to different company details. Reload to see the saved company.'},409);}
  }else if(body.action==='status'){
   if(profile.role!=='admin')return response({error:'Only administrators can change status.'},403);if(typeof body.id!=='string'||!['Active','Pending','Inactive'].includes(body.status))return response({error:'Choose a valid status.'},400);const changed=await db.prepare('UPDATE vendors SET status=? WHERE id=?').bind(body.status,body.id).run();if(!changed.meta.changes)return response({error:'Vendor not found.'},404);
  }else if(body.action==='review'){
   if(profile.role!=='admin')return response({error:'Only administrators can evaluate vendors.'},403);const parsed=reviewInput.safeParse(body.data);if(!parsed.success)return response({error:'Choose a score from 1 to 5 for all five criteria.'},400);const r=parsed.data;if(!await db.prepare('SELECT id FROM vendors WHERE id=?').bind(r.vendorId).first())return response({error:'Vendor not found.'},404);
   const previous=await db.prepare('SELECT vendor_id AS vendorId,reviewer_id AS reviewerId,quality,price,delivery,service,reliability,comment FROM reviews WHERE id=?').bind(r.id).first<Record<string,unknown>>();if(previous&&(previous.reviewerId!==user.userId||Object.entries(r).some(([key,value])=>key!=='id'&&previous[key]!==value)))return response({error:'An evaluation was already saved with different scores. Reload to see it before starting a new evaluation.'},409);
   await db.prepare('INSERT OR IGNORE INTO reviews (id,vendor_id,reviewer_id,reviewer,quality,price,delivery,service,reliability,comment,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(r.id,r.vendorId,user.userId,profile.name,r.quality,r.price,r.delivery,r.service,r.reliability,r.comment,now).run();
   const saved=await db.prepare('SELECT vendor_id AS vendorId,reviewer_id AS reviewerId,quality,price,delivery,service,reliability,comment FROM reviews WHERE id=?').bind(r.id).first<Record<string,unknown>>();if(!saved||saved.reviewerId!==user.userId||Object.entries(r).some(([key,value])=>key!=='id'&&saved[key]!==value))return response({error:'An evaluation was already saved with different scores. Reload to see it before starting a new evaluation.'},409);
  }else{return response({error:'Unknown action.'},400);}
 }
 return response(await state(user.userId));
 }catch(error){console.error('Workspace save failed',error);return response({error:'We could not save your changes. Your input is still here; please try again.'},503);}}
